In [1]:
!pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("Tensor A:\n",A)
print("Tensor B:\n",B)
add_result=A+B
sub_result=A-B
mul_result=A*B
div_result=A/B
matmul_result=A@B
print("\n Addition:\n",add_result)
print("\n Subtraction:\n",sub_result)
print("\n Multiplication:\n",mul_result)
print("\n Division:\n",div_result)
print("\n Matmul:\n",matmul_result)

Tensor A:
 [[1 2]
 [3 4]]
Tensor B:
 [[5 6]
 [7 8]]

 Addition:
 [[ 6  8]
 [10 12]]

 Subtraction:
 [[-4 -4]
 [-4 -4]]

 Multiplication:
 [[ 5 12]
 [21 32]]

 Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]

 Matmul:
 [[19 22]
 [43 50]]


In [3]:
import tensorflow as tf
A=tf.constant([[1,2],[3,4]],dtype=tf.float32)
B=tf.constant([[5,6],[7,8]],dtype=tf.float32)
add_result=tf.add(A,B)
sub_result=tf.subtract(A,B)
mul_result=tf.multiply(A,B)
div_result=tf.divide(A,B)
matmul_result=tf.matmul(A,B)
print("\n Addition:\n",add_result.numpy())
print("\n Subtraction:\n",sub_result.numpy())
print("\n Multiplication:\n",mul_result.numpy())
print("\n Division:\n",div_result.numpy())
print("\n Matmul:\n",matmul_result.numpy())



 Addition:
 [[ 6.  8.]
 [10. 12.]]

 Subtraction:
 [[-4. -4.]
 [-4. -4.]]

 Multiplication:
 [[ 5. 12.]
 [21. 32.]]

 Division:
 [[0.2        0.33333334]
 [0.42857143 0.5       ]]

 Matmul:
 [[19. 22.]
 [43. 50.]]


In [4]:
 tf.rank(A)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [5]:
A.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [6]:
import numpy as np
data=np.arange(1,13).reshape(3,4)
print("Original Tensor:\n",data)
splits=np.split(data,2,axis=1)
for part in splits:
    print(part)
merged=np.concatenate(splits,axis=1)
print("\n Merged Tensor:\n",merged)

Original Tensor:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]

 Merged Tensor:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
import numpy as np
data=np.arange(1,26).reshape(5,5)
print("Original Tensor:\n",data)
splits=np.split(data,5,axis=1)
print("\nSplit Parts:")
for part in splits:
    print(part)
merged=np.concatenate(splits,axis=1)
print("\nMerged Tensor:\n",merged)
mean_val=np.mean(data)
max_val=np.max(data)
min_val=np.min(data)
sum_val=np.sum(data)
std_val=np.std(data)
print("\n Statistics:")
print(f"Mean:{mean_val}")
print(f"Max:{max_val}")
print(f"Min:{min_val}")
print(f"Sum:{sum_val}")
print(f"Standard Deviation:{std_val}")


Original Tensor:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Split Parts:
[[ 1]
 [ 6]
 [11]
 [16]
 [21]]
[[ 2]
 [ 7]
 [12]
 [17]
 [22]]
[[ 3]
 [ 8]
 [13]
 [18]
 [23]]
[[ 4]
 [ 9]
 [14]
 [19]
 [24]]
[[ 5]
 [10]
 [15]
 [20]
 [25]]

Merged Tensor:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

 Statistics:
Mean:13.0
Max:25
Min:1
Sum:325
Standard Deviation:7.211102550927978


In [29]:
import tensorflow as tf
data=tf.constant([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype=tf.float32)
print("Original Tensor:\n",data.numpy())
splits=tf.split(data,num_or_size_splits=2,axis=1)
print("\nSplit Parts:")
for part in splits:
    print(part.numpy())
merged=tf.concat(splits,axis=1)
print("\nMerged Tensor:\n",merged.numpy())
mean_val=tf.reduce_mean(data)
max_val=tf.reduce_max(data)
min_val=tf.reduce_min(data)
sum_val=tf.reduce_sum(data)
std_val=tf.math.reduce_std(data)
print("\nStatistics:")
print(f"Mean:{mean_val.numpy()}")
print(f"Max:{max_val.numpy()}")
print(f"Min:{min_val.numpy()}")
print(f"Sum:{sum_val.numpy()}")
print(f"Standard Deviation:{std_val.numpy()}")

Original Tensor:
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]

Split Parts:
[[ 1.  2.]
 [ 5.  6.]
 [ 9. 10.]]
[[ 3.  4.]
 [ 7.  8.]
 [11. 12.]]

Merged Tensor:
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]

Statistics:
Mean:6.5
Max:12.0
Min:1.0
Sum:78.0
Standard Deviation:3.452052593231201


In [30]:
X=tf.constant([[0.0,0.0],
               [0.0,1.0],
               [1.0,0.0],
               [1.0,1.0]],dtype=tf.float32)

In [31]:
W=tf.constant([[-2.0],
               [-2.0]],
             dtype=tf.float32)

In [32]:
b=tf.constant([-3.0],dtype=tf.float32)#bias

In [33]:
z=tf.matmul(X,W)+b

In [34]:
y_step=tf.cast(z >= 0,tf.int32)#binary output
y_sigmoid=tf.math.sigmoid(z)
print("Inputs:\n",X.numpy())
print("Linear combination (z):\n",z.numpy())
print("Step output (Perceptron):\n",y_step.numpy())
print("sigmoid output(probability):\n",y_sigmoid.numpy())


Inputs:
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Linear combination (z):
 [[-3.]
 [-5.]
 [-5.]
 [-7.]]
Step output (Perceptron):
 [[0]
 [0]
 [0]
 [0]]
sigmoid output(probability):
 [[0.04742587]
 [0.00669285]
 [0.00669285]
 [0.00091105]]


In [37]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [38]:
df=pd.read_csv("iris.csv")
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [156]:
X=df.iloc[:, 0:1].values
y=df.iloc[:, -1].values

In [157]:
y_binary=np.where(y=="versicolor",1.0,0.0).astype(np.float32)
y_binary

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [158]:
X=(X-X.mean(axis=0))/X.std(axis=0)
X

array([[-0.90068117],
       [-1.14301691],
       [-1.38535265],
       [-1.50652052],
       [-1.02184904],
       [-0.53717756],
       [-1.50652052],
       [-1.02184904],
       [-1.74885626],
       [-1.14301691],
       [-0.53717756],
       [-1.26418478],
       [-1.26418478],
       [-1.87002413],
       [-0.05250608],
       [-0.17367395],
       [-0.53717756],
       [-0.90068117],
       [-0.17367395],
       [-0.90068117],
       [-0.53717756],
       [-0.90068117],
       [-1.50652052],
       [-0.90068117],
       [-1.26418478],
       [-1.02184904],
       [-1.02184904],
       [-0.7795133 ],
       [-0.7795133 ],
       [-1.38535265],
       [-1.26418478],
       [-0.53717756],
       [-0.7795133 ],
       [-0.41600969],
       [-1.14301691],
       [-1.02184904],
       [-0.41600969],
       [-1.14301691],
       [-1.74885626],
       [-0.90068117],
       [-1.02184904],
       [-1.62768839],
       [-1.74885626],
       [-1.02184904],
       [-0.90068117],
       [-1

In [159]:
X_tf=tf.constant(X, dtype=tf.float32)
X_tf

<tf.Tensor: shape=(150, 1), dtype=float32, numpy=
array([[-0.9006812 ],
       [-1.1430169 ],
       [-1.3853526 ],
       [-1.5065205 ],
       [-1.021849  ],
       [-0.53717756],
       [-1.5065205 ],
       [-1.021849  ],
       [-1.7488563 ],
       [-1.1430169 ],
       [-0.53717756],
       [-1.2641848 ],
       [-1.2641848 ],
       [-1.8700241 ],
       [-0.05250608],
       [-0.17367394],
       [-0.53717756],
       [-0.9006812 ],
       [-0.17367394],
       [-0.9006812 ],
       [-0.53717756],
       [-0.9006812 ],
       [-1.5065205 ],
       [-0.9006812 ],
       [-1.2641848 ],
       [-1.021849  ],
       [-1.021849  ],
       [-0.7795133 ],
       [-0.7795133 ],
       [-1.3853526 ],
       [-1.2641848 ],
       [-0.53717756],
       [-0.7795133 ],
       [-0.4160097 ],
       [-1.1430169 ],
       [-1.021849  ],
       [-0.4160097 ],
       [-1.1430169 ],
       [-1.7488563 ],
       [-0.9006812 ],
       [-1.021849  ],
       [-1.6276884 ],
       [-1.7488563 ],
    

In [160]:
W=tf.constant([[1,0],[-1,0]],dtype=tf.float32)
W

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.,  0.],
       [-1.,  0.]], dtype=float32)>

In [161]:
b=tf.constant([0.2],dtype=tf.float32)

In [162]:
z=tf.matmul(X_tf,W)+b

InvalidArgumentError: {{function_node __wrapped____MklMatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [150,1], In[1]: [2,2] [Op:MatMul] name: 

In [110]:
X_tf.shape

TensorShape([150, 2])

In [111]:
W.shape

TensorShape([2, 2])

In [112]:
y_pred_step=tf.cast(z>=0,tf.int32)

In [113]:
y_pred_sigmoid=tf.math.sigmoid(z)

In [114]:
print("First 10 True labels(Setosa=1,others=0):",y_binary[:10])
print("First 10 step outputs:",y_pred_step.numpy().flatten()[:10])
print("First 10 sigmoid probabilities:",y_pred_sigmoid.numpy().flatten()[:10])

First 10 True labels(Setosa=1,others=0): [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
First 10 step outputs: [0 1 0 1 0 1 0 1 0 1]
First 10 sigmoid probabilities: [0.15023766 0.549834   0.30617577 0.549834   0.17899066 0.549834
 0.1957667  0.549834   0.1105329  0.549834  ]
